<a href="https://colab.research.google.com/github/PerfectMach1ne/uni-ai-ml/blob/main/25_10_23_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 25.10.23, part II
## Numpyyy!!!!
les go

In [1]:
import numpy as np

In [3]:
arr_1 = np.array([1, 2, 3, 4]) # tworzenie na podst. listy
print("Typ tablicy: ", type(arr_1))
print("Tablica 1D: ",arr_1)

arr_1 = np.array((1, 2, 3, 4)) # tw. na podst. krotki
print("Typ tablicy: ", type(arr_1))
print("Tablica 1D: ",arr_1)

Typ tablicy:  <class 'numpy.ndarray'>
Tablica 1D:  [1 2 3 4]
Typ tablicy:  <class 'numpy.ndarray'>
Tablica 1D:  [1 2 3 4]


#### Typowe funkcje matrycowe:

In [4]:
arr_2=np.zeros(5)
arr_3=np.ones(5)
arr_4=np.full(5,3)
arr_5=np.arange(10)
print("Tablica wypleniona 0: ", arr_2)
print("Tablica wypleniona 1: ", arr_3)
print("Tablica wypleniona 3: ", arr_4)
print("Tablica wypleniona liczbami od 0 do 9: ", arr_5)

Tablica wypleniona 0:  [0. 0. 0. 0. 0.]
Tablica wypleniona 1:  [1. 1. 1. 1. 1.]
Tablica wypleniona 3:  [3 3 3 3 3]
Tablica wypleniona liczbami od 0 do 9:  [0 1 2 3 4 5 6 7 8 9]


In [5]:
# arr_6 = np.zeros(2,3)

TypeError: ignored

In [6]:
print("Cala tablica 1D: ", arr_1)
print("Liczba elementow w tablicy: ", len(arr_1))
print("Pierwszy element tablicy: ", arr_1[0])
print("Ostatni element tablicy: ", arr_1[-1])
print("Dwa pierwsze elementy w tablicy: ", arr_1[0:2])
print("Dwa ostatnie elementy w tablicy: ", arr_1[-2:])
print("Elementy znajdujące się pod parzystymi indeksami: ", arr_1[::2])
arr_1[0]=100
print("Cala tablica 1D po modyfikacji: ", arr_1)

Cala tablica 1D:  [1 2 3 4]
Liczba elementow w tablicy:  4
Pierwszy element tablicy:  1
Ostatni element tablicy:  4
Dwa pierwsze elementy w tablicy:  [1 2]
Dwa ostatnie elementy w tablicy:  [3 4]
Elementy znajdujące się pod parzystymi indeksami:  [1 3]
Cala tablica 1D po modyfikacji:  [100   2   3   4]


In [7]:
arr_1 = np.array([1, 2, 3, 4])
arr_2 = np.array([-1, -2, -3, -4])
print("Tablica arr_1: ", arr_1)
print("Tablica arr_2: ", arr_2)

res=arr_1+arr_2
print("arr_1 + arr_2: ", res)
res=arr_1*arr_2
print("arr_1 * arr_2: ", res)

Tablica arr_1:  [1 2 3 4]
Tablica arr_2:  [-1 -2 -3 -4]
arr_1 + arr_2:  [0 0 0 0]
arr_1 * arr_2:  [ -1  -4  -9 -16]


In [11]:
print("średnia arr_1: ", arr_1.mean())
print("Max arr_1: ", arr_1.max())
print("średnia arr_2: ", arr_2.mean())
print("średnia res: ", res.mean())
print("max res: ", res.max())

średnia arr_1:  2.5
Max arr_1:  4
średnia arr_2:  -2.5
średnia res:  -7.5
max res:  -1


#### Idea maski

In [12]:
mask=arr_1>1
print("Tablica 1D: ", arr_1)
print("Czy element wiekszy od 1? ", mask)
print("Liczba elementow wieksza od 1: ", mask.sum())
print("Elementy ktora sa wieksze od 1: ", arr_1[mask])

Tablica 1D:  [1 2 3 4]
Czy element wiekszy od 1?  [False  True  True  True]
Liczba elementow wieksza od 1:  3
Elementy ktora sa wieksze od 1:  [2 3 4]


In [13]:
mask_0 = arr_1>=3
print(mask_0)

[False False  True  True]


In [14]:
mask_1=arr_1!=4
print(mask_1)

[ True  True  True False]


#### enumerate() na tablicy

In [15]:
for i,el in enumerate(arr_1):
  print(f"{i} element w tablicy: {el}")

0 element w tablicy: 1
1 element w tablicy: 2
2 element w tablicy: 3
3 element w tablicy: 4


### Tablice 2D!!!!

In [19]:
arr_5=np.array([[2,3,5,1], [5,1,2,8], [5,1,6,-1]])
print("Tablica 2D: \n", arr_5)

Tablica 2D: 
 [[ 2  3  5  1]
 [ 5  1  2  8]
 [ 5  1  6 -1]]


In [18]:
print("Wymiary tablicy: ", arr_5.shape)
print("Element o wspolrzednych 0,0: ", arr_5[0,0])
print("Pierwsza kolumn: ", arr_5[:,0])
print("Pierwszy wiersz: ", arr_5[0,:])
print("Obszar tablicy: \n", arr_5[0:2, 1:3])
print("Parzyste kolumny: \n", arr_5[:, ::2])
print("Parzyste wiersze: \n",arr_5[::2,:])

Wymiary tablicy:  (3, 4)
Element o wspolrzednych 0,0:  2
Pierwsza kolumn:  [2 5 5]
Pierwszy wiersz:  [2 3 5 1]
Obszar tablicy: 
 [[3 5]
 [1 2]]
Parzyste kolumny: 
 [[2 5]
 [5 2]
 [5 6]]
Parzyste wiersze: 
 [[ 2  3  5  1]
 [ 5  1  6 -1]]


In [20]:
s_cols=arr_5.sum(axis=0)
s_rows=arr_5.sum(axis=1)
print(f"Suma elementow w poszczegolnych kolumnach jest rowna {s_cols}, a w wierszach {s_rows}")

Suma elementow w poszczegolnych kolumnach jest rowna [12  5 13  8], a w wierszach [11 16 11]


In [21]:
mask=arr_5>4
print("Maska: \n",mask)
print("Elementy >4: \n", arr_5[mask])

Maska: 
 [[False False  True False]
 [ True False False  True]
 [ True False  True False]]
Elementy >4: 
 [5 5 8 5 6]


In [22]:
# oo ciekawe
index_cols=[1,-1]
selected_cols=arr_5[:,index_cols]
print("Druga i ostatnia kolumna: \n", selected_cols)

Druga i ostatnia kolumna: 
 [[ 3  1]
 [ 1  8]
 [ 1 -1]]


In [23]:

print("Tablica z podzialem na wiersze")
for i,row in enumerate(arr_5):
  print(f"Wiersz {i}: {row}")

Tablica z podzialem na wiersze
Wiersz 0: [2 3 5 1]
Wiersz 1: [5 1 2 8]
Wiersz 2: [ 5  1  6 -1]


In [24]:
print("Tablica element po elemencie")
for row in arr_5: # it's bc of how np arrays are structured, for reads rows first
  for el in row:
    print(el, end=" ")
  print() # for a new line

Tablica element po elemencie
2 3 5 1 
5 1 2 8 
5 1 6 -1 


#### zmiana wymiarów tablic

In [25]:
arr_1=np.array([1,2,3,4])
print("Tablica przed zmiana ksztaltu: ",arr_1)

arr_2=arr_1.reshape(2,2)
print("Tablica po zmianie: ",arr_2)

arr_3=arr_2.reshape(4)
print("Tablica po kolejnej zmianie: ",arr_3)

Tablica przed zmiana ksztaltu:  [1 2 3 4]
Tablica po zmianie:  [[1 2]
 [3 4]]
Tablica po kolejnej zmianie:  [1 2 3 4]


In [29]:
arr_4 = arr_3.reshape(4,1)
print(arr_4)

[[1]
 [2]
 [3]
 [4]]


#### dodawanie/usuwanie wymiarów

In [30]:
arr_1=np.array([1,2,3,4])
print("Przed expand_dims: \n",arr_1)
arr_2=np.expand_dims(arr_1, axis=0)
print("Po expand_dims, axis=0: \n",arr_2)
arr_3=np.expand_dims(arr_1, axis=1)
print("Po expand_dims, axis=1: \n",arr_3)

print("Przed squeeze, axis=0: \n",arr_2)
arr_4=np.squeeze(arr_2, axis=0)
print("Po squeeze, axis=0: \n",arr_4)

print("Przed squeeze, axis=1: \n",arr_3)
arr_5=np.squeeze(arr_3, axis=1)
print("Po squeeze, axis=1: \n",arr_5)

Przed expand_dims: 
 [1 2 3 4]
Po expand_dims, axis=0: 
 [[1 2 3 4]]
Po expand_dims, axis=1: 
 [[1]
 [2]
 [3]
 [4]]
Przed squeeze, axis=0: 
 [[1 2 3 4]]
Po squeeze, axis=0: 
 [1 2 3 4]
Przed squeeze, axis=1: 
 [[1]
 [2]
 [3]
 [4]]
Po squeeze, axis=1: 
 [1 2 3 4]


In [31]:
arr_1=np.array([1,2,3,4])
print(arr_1)

[1 2 3 4]


In [32]:
arr_1=np.expand_dims(arr_1, axis=1)
print(arr_1)

[[1]
 [2]
 [3]
 [4]]


In [33]:
arr_1=np.squeeze(arr_1, axis=0)

ValueError: ignored

In [34]:
arr_1=np.squeeze(arr_1, axis=1)

In [35]:
print(arr_1)

[1 2 3 4]


### zadanka 1-4

In [77]:
arr_kroki=np.array((515.1, 314.3, 4324.0, 53.1, 128.3, 444.4, 712.8, 951,3, 432.5, 670.2, 98.5))

In [37]:
arr_kroki

array([5.151e+02, 3.143e+02, 4.324e+03, 5.310e+01, 1.283e+02, 4.444e+02,
       7.128e+02, 9.510e+02, 3.000e+00, 4.325e+02, 6.702e+02, 9.850e+01])

In [38]:
print(arr_kroki.mean())

720.6


In [39]:
print(arr_kroki<arr_kroki.mean())

[ True  True False  True  True  True  True False  True  True  True  True]


In [42]:
print(arr_kroki>30000.0) # LMAO

[False False False False False False False False False False False False]


In [47]:
for e in arr_kroki:
  print(e, end=" ")

515.1 314.3 4324.0 53.1 128.3 444.4 712.8 951.0 3.0 432.5 670.2 98.5 

In [46]:
# print(!arr_kroki>30000.0)
# print(arr_kroki!>30000.0)
print(arr_kroki<=30000.0) # big math brain lol

[ True  True  True  True  True  True  True  True  True  True  True  True]


### zadanka 5-10

In [84]:
arr_wydatki = np.array([
    [190.55, 180.42, 123.31, 90.98, 150.21, 110.10, 230.12, 130.34, 153.27, 400.31, 200.35, 300.03],
    [32.12, 175.10, 240.32, 6.77, 400.12, 120.13, 245.23, 140.13, 182.98, 194.32, 567.12, 131.20],
    [322.12, 15.10, 20.32, 16.77, 40.12, 10.13, 45.23, 40.13, 82.98, 14.32, 57.12, 11.20],
    [2.12, 5.10, 2.32, 156.77, 410.12, 132.13, 13.23, 14.13, 18.98, 141.32, 5.12, 111.20]
])

In [62]:
# # print(arr_wydatki)
# print(arr_wydatki.shape)
# (rows,cols) = arr_wydatki.shape
# print(cols,rows)
# for i, col in enumerate(arr_wydatki.reshape(cols,rows)):
#   print(f"miesiąc {i+1}: ", end='')
#   for row in col:
#     print(row, end="PLN ")
#   print()
# -============================ ZJEBANE

(4, 12)
12 4
miesiąc 1: 190.55PLN 180.42PLN 123.31PLN 90.98PLN 
miesiąc 2: 150.21PLN 110.1PLN 230.12PLN 130.34PLN 
miesiąc 3: 153.27PLN 400.31PLN 200.35PLN 300.03PLN 
miesiąc 4: 32.12PLN 175.1PLN 240.32PLN 6.77PLN 
miesiąc 5: 400.12PLN 120.13PLN 245.23PLN 140.13PLN 
miesiąc 6: 182.98PLN 194.32PLN 567.12PLN 131.2PLN 
miesiąc 7: 322.12PLN 15.1PLN 20.32PLN 16.77PLN 
miesiąc 8: 40.12PLN 10.13PLN 45.23PLN 40.13PLN 
miesiąc 9: 82.98PLN 14.32PLN 57.12PLN 11.2PLN 
miesiąc 10: 2.12PLN 5.1PLN 2.32PLN 156.77PLN 
miesiąc 11: 410.12PLN 132.13PLN 13.23PLN 14.13PLN 
miesiąc 12: 18.98PLN 141.32PLN 5.12PLN 111.2PLN 


In [80]:
# for i, col in enumerate(arr_wydatki.reshape(cols,rows)):
  # print(f"Średnie wydatki w m-cu {i+1} = " + str(col.mean()) + "PLN")
# ================================================ ZJEBANEEE

Średnie wydatki w m-cu 1 = 146.315PLN
Średnie wydatki w m-cu 2 = 155.1925PLN
Średnie wydatki w m-cu 3 = 263.49PLN
Średnie wydatki w m-cu 4 = 113.57749999999999PLN
Średnie wydatki w m-cu 5 = 226.4025PLN
Średnie wydatki w m-cu 6 = 268.905PLN
Średnie wydatki w m-cu 7 = 93.5775PLN
Średnie wydatki w m-cu 8 = 33.902499999999996PLN
Średnie wydatki w m-cu 9 = 41.405PLN
Średnie wydatki w m-cu 10 = 41.5775PLN
Średnie wydatki w m-cu 11 = 142.4025PLN
Średnie wydatki w m-cu 12 = 69.155PLN


In [82]:
print("Roczne wydatki = " + str(arr_wydatki.sum()) + "PLN")

Roczne wydatki = 6383.61PLN


In [85]:
print("Wydatki na lipiec i sierpień: \n" + str(arr_wydatki[:,6:8]))

Wydatki na lipiec i sierpień: 
[[230.12 130.34]
 [245.23 140.13]
 [ 45.23  40.13]
 [ 13.23  14.13]]


In [86]:
print(arr_wydatki.transpose())

[[190.55  32.12 322.12   2.12]
 [180.42 175.1   15.1    5.1 ]
 [123.31 240.32  20.32   2.32]
 [ 90.98   6.77  16.77 156.77]
 [150.21 400.12  40.12 410.12]
 [110.1  120.13  10.13 132.13]
 [230.12 245.23  45.23  13.23]
 [130.34 140.13  40.13  14.13]
 [153.27 182.98  82.98  18.98]
 [400.31 194.32  14.32 141.32]
 [200.35 567.12  57.12   5.12]
 [300.03 131.2   11.2  111.2 ]]


In [90]:
# print(arr_wydatki)
arr_wydatki.transpose()
# print(arr_wydatki)
arr_wydatki_T = arr_wydatki.transpose()
print(arr_wydatki_T)
print()
for i, col in enumerate(arr_wydatki_T):
  print(f"miesiąc {i+1}: ", end='')
  for row in col:
    print(row, end="PLN ")
  print()

[[190.55  32.12 322.12   2.12]
 [180.42 175.1   15.1    5.1 ]
 [123.31 240.32  20.32   2.32]
 [ 90.98   6.77  16.77 156.77]
 [150.21 400.12  40.12 410.12]
 [110.1  120.13  10.13 132.13]
 [230.12 245.23  45.23  13.23]
 [130.34 140.13  40.13  14.13]
 [153.27 182.98  82.98  18.98]
 [400.31 194.32  14.32 141.32]
 [200.35 567.12  57.12   5.12]
 [300.03 131.2   11.2  111.2 ]]

miesiąc 1: 190.55PLN 32.12PLN 322.12PLN 2.12PLN 
miesiąc 2: 180.42PLN 175.1PLN 15.1PLN 5.1PLN 
miesiąc 3: 123.31PLN 240.32PLN 20.32PLN 2.32PLN 
miesiąc 4: 90.98PLN 6.77PLN 16.77PLN 156.77PLN 
miesiąc 5: 150.21PLN 400.12PLN 40.12PLN 410.12PLN 
miesiąc 6: 110.1PLN 120.13PLN 10.13PLN 132.13PLN 
miesiąc 7: 230.12PLN 245.23PLN 45.23PLN 13.23PLN 
miesiąc 8: 130.34PLN 140.13PLN 40.13PLN 14.13PLN 
miesiąc 9: 153.27PLN 182.98PLN 82.98PLN 18.98PLN 
miesiąc 10: 400.31PLN 194.32PLN 14.32PLN 141.32PLN 
miesiąc 11: 200.35PLN 567.12PLN 57.12PLN 5.12PLN 
miesiąc 12: 300.03PLN 131.2PLN 11.2PLN 111.2PLN 


In [97]:
wydatki_miesieczne = [row.sum() for row in arr_wydatki_T]
print(wydatki_miesieczne)
mask = np.array(wydatki_miesieczne)
print(mask>1000.0)
mask_res = mask>1000.0
i = 0
for v in mask_res:
  if v:
    i = i + 1
print("Ile wydatków > 1000PLN: ", i)

print(mask>500.0)
mask_res = mask>500.0
i = 0
for v in mask_res:
  if v:
    i = i + 1
print("Ile wydatków > 500PLN: ", i)

[546.91, 375.72, 386.27, 271.29, 1000.57, 372.49, 533.8100000000001, 324.73, 438.21000000000004, 750.27, 829.71, 553.63]
[False False False False  True False False False False False False False]
Ile wydatków > 1000PLN:  1
[ True False False False  True False  True False False  True  True  True]
Ile wydatków > 500PLN:  6


In [101]:
print("Średnia roczna wydatków: " + str(arr_wydatki.mean()) + "PLN")
sr_roczna = arr_wydatki.mean()
mask_ponizej_sr_rocznej = arr_wydatki_T<sr_roczna
print(mask_ponizej_sr_rocznej)

Średnia roczna wydatków: 132.991875PLN
[[False  True False  True]
 [False False  True  True]
 [ True False  True  True]
 [ True  True  True False]
 [False False  True False]
 [ True  True  True  True]
 [False False  True  True]
 [ True False  True  True]
 [False False  True  True]
 [False False  True False]
 [False False  True  True]
 [False  True  True  True]]


this was so fucking cool. I am feeling opposite of burnt out now. very good. big excite. excite excite excite!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!11
(mabe it;ll help me pass this class lol)